apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: jelastic-dynamic-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4050Mi
